# Generated by Django 2.2.6 on 2020-07-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField()),
                ('Email', models.TextField(unique=True)),
                ('Password', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classLabel', models.TextField()),
                ('fileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageClassification.Files')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageClassification.Users'),
        ),
    ]
